// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnfgDaMSWtt0wvTVFZY-vfCSgxNN3Wdwg',
    appId: '1:778847219019:web:b0b20ddeb1f3282301ccce',
    messagingSenderId: '778847219019',
    projectId: 'flutter-task-19ec0',
    authDomain: 'flutter-task-19ec0.firebaseapp.com',
    storageBucket: 'flutter-task-19ec0.appspot.com',
    measurementId: 'G-D5J7J67CJ2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBoy9JNWBzr9JhQR1KccEsm2SPd7TDyq_c',
    appId: '1:778847219019:android:5f3364a6be49808901ccce',
    messagingSenderId: '778847219019',
    projectId: 'flutter-task-19ec0',
    storageBucket: 'flutter-task-19ec0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1esb2WV69Rs1ohviy9-hjEClUBZ79yFg',
    appId: '1:778847219019:ios:ae198ead5ecd2c5e01ccce',
    messagingSenderId: '778847219019',
    projectId: 'flutter-task-19ec0',
    storageBucket: 'flutter-task-19ec0.appspot.com',
    iosClientId: '778847219019-prtvop4cfv0ga64jsvi0be7ut4m3u006.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterTask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1esb2WV69Rs1ohviy9-hjEClUBZ79yFg',
    appId: '1:778847219019:ios:ae198ead5ecd2c5e01ccce',
    messagingSenderId: '778847219019',
    projectId: 'flutter-task-19ec0',
    storageBucket: 'flutter-task-19ec0.appspot.com',
    iosClientId: '778847219019-prtvop4cfv0ga64jsvi0be7ut4m3u006.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterTask',
  );
}
